/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as SalariesRouteImport } from './routes/salaries'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ExtraIncomesRouteImport } from './routes/extra-incomes'
import { Route as DebtsRouteImport } from './routes/debts'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as CashbacksRouteImport } from './routes/cashbacks'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BanksRouteImport } from './routes/banks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedIdRouteImport } from './routes/shared_.$id'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksPaymentChecksRouteImport } from './routes/api/public/hooks/payment-checks'
import { Route as ApiPublicHooksDailyRemindersRouteImport } from './routes/api/public/hooks/daily-reminders'
import { Route as ApiPublicHooksCashbackRemindersRouteImport } from './routes/api/public/hooks/cashback-reminders'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesRoute = SalariesRouteImport.update({
  id: '/salaries',
  path: '/salaries',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtraIncomesRoute = ExtraIncomesRouteImport.update({
  id: '/extra-incomes',
  path: '/extra-incomes',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsRoute = DebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const CashbacksRoute = CashbacksRouteImport.update({
  id: '/cashbacks',
  path: '/cashbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksRoute = BanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedIdRoute = SharedIdRouteImport.update({
  id: '/shared_/$id',
  path: '/shared/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPaymentChecksRoute =
  ApiPublicHooksPaymentChecksRouteImport.update({
    id: '/api/public/hooks/payment-checks',
    path: '/api/public/hooks/payment-checks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyRemindersRoute =
  ApiPublicHooksDailyRemindersRouteImport.update({
    id: '/api/public/hooks/daily-reminders',
    path: '/api/public/hooks/daily-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCashbackRemindersRoute =
  ApiPublicHooksCashbackRemindersRouteImport.update({
    id: '/api/public/hooks/cashback-reminders',
    path: '/api/public/hooks/cashback-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/auth': typeof AuthRoute
  '/banks': typeof BanksRoute
  '/calendar': typeof CalendarRoute
  '/cashbacks': typeof CashbacksRoute
  '/credits': typeof CreditsRoute
  '/debts': typeof DebtsRoute
  '/extra-incomes': typeof ExtraIncomesRoute
  '/goals': typeof GoalsRoute
  '/profile': typeof ProfileRoute
  '/reminders': typeof RemindersRoute
  '/salaries': typeof SalariesRoute
  '/shared': typeof SharedRoute
  '/shifts': typeof ShiftsRoute
  '/stats': typeof StatsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/transactions': typeof TransactionsRoute
  '/shared/$id': typeof SharedIdRoute
  '/api/public/hooks/cashback-reminders': typeof ApiPublicHooksCashbackRemindersRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
  '/api/public/hooks/payment-checks': typeof ApiPublicHooksPaymentChecksRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/auth': typeof AuthRoute
  '/banks': typeof BanksRoute
  '/calendar': typeof CalendarRoute
  '/cashbacks': typeof CashbacksRoute
  '/credits': typeof CreditsRoute
  '/debts': typeof DebtsRoute
  '/extra-incomes': typeof ExtraIncomesRoute
  '/goals': typeof GoalsRoute
  '/profile': typeof ProfileRoute
  '/reminders': typeof RemindersRoute
  '/salaries': typeof SalariesRoute
  '/shared': typeof SharedRoute
  '/shifts': typeof ShiftsRoute
  '/stats': typeof StatsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/transactions': typeof TransactionsRoute
  '/shared/$id': typeof SharedIdRoute
  '/api/public/hooks/cashback-reminders': typeof ApiPublicHooksCashbackRemindersRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
  '/api/public/hooks/payment-checks': typeof ApiPublicHooksPaymentChecksRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/auth': typeof AuthRoute
  '/banks': typeof BanksRoute
  '/calendar': typeof CalendarRoute
  '/cashbacks': typeof CashbacksRoute
  '/credits': typeof CreditsRoute
  '/debts': typeof DebtsRoute
  '/extra-incomes': typeof ExtraIncomesRoute
  '/goals': typeof GoalsRoute
  '/profile': typeof ProfileRoute
  '/reminders': typeof RemindersRoute
  '/salaries': typeof SalariesRoute
  '/shared': typeof SharedRoute
  '/shifts': typeof ShiftsRoute
  '/stats': typeof StatsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/transactions': typeof TransactionsRoute
  '/shared_/$id': typeof SharedIdRoute
  '/api/public/hooks/cashback-reminders': typeof ApiPublicHooksCashbackRemindersRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
  '/api/public/hooks/payment-checks': typeof ApiPublicHooksPaymentChecksRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/ai-insights'
    | '/auth'
    | '/banks'
    | '/calendar'
    | '/cashbacks'
    | '/credits'
    | '/debts'
    | '/extra-incomes'
    | '/goals'
    | '/profile'
    | '/reminders'
    | '/salaries'
    | '/shared'
    | '/shifts'
    | '/stats'
    | '/subscriptions'
    | '/transactions'
    | '/shared/$id'
    | '/api/public/hooks/cashback-reminders'
    | '/api/public/hooks/daily-reminders'
    | '/api/public/hooks/payment-checks'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/ai-insights'
    | '/auth'
    | '/banks'
    | '/calendar'
    | '/cashbacks'
    | '/credits'
    | '/debts'
    | '/extra-incomes'
    | '/goals'
    | '/profile'
    | '/reminders'
    | '/salaries'
    | '/shared'
    | '/shifts'
    | '/stats'
    | '/subscriptions'
    | '/transactions'
    | '/shared/$id'
    | '/api/public/hooks/cashback-reminders'
    | '/api/public/hooks/daily-reminders'
    | '/api/public/hooks/payment-checks'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/ai-insights'
    | '/auth'
    | '/banks'
    | '/calendar'
    | '/cashbacks'
    | '/credits'
    | '/debts'
    | '/extra-incomes'
    | '/goals'
    | '/profile'
    | '/reminders'
    | '/salaries'
    | '/shared'
    | '/shifts'
    | '/stats'
    | '/subscriptions'
    | '/transactions'
    | '/shared_/$id'
    | '/api/public/hooks/cashback-reminders'
    | '/api/public/hooks/daily-reminders'
    | '/api/public/hooks/payment-checks'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AuthRoute: typeof AuthRoute
  BanksRoute: typeof BanksRoute
  CalendarRoute: typeof CalendarRoute
  CashbacksRoute: typeof CashbacksRoute
  CreditsRoute: typeof CreditsRoute
  DebtsRoute: typeof DebtsRoute
  ExtraIncomesRoute: typeof ExtraIncomesRoute
  GoalsRoute: typeof GoalsRoute
  ProfileRoute: typeof ProfileRoute
  RemindersRoute: typeof RemindersRoute
  SalariesRoute: typeof SalariesRoute
  SharedRoute: typeof SharedRoute
  ShiftsRoute: typeof ShiftsRoute
  StatsRoute: typeof StatsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TransactionsRoute: typeof TransactionsRoute
  SharedIdRoute: typeof SharedIdRoute
  ApiPublicHooksCashbackRemindersRoute: typeof ApiPublicHooksCashbackRemindersRoute
  ApiPublicHooksDailyRemindersRoute: typeof ApiPublicHooksDailyRemindersRoute
  ApiPublicHooksPaymentChecksRoute: typeof ApiPublicHooksPaymentChecksRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries': {
      id: '/salaries'
      path: '/salaries'
      fullPath: '/salaries'
      preLoaderRoute: typeof SalariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extra-incomes': {
      id: '/extra-incomes'
      path: '/extra-incomes'
      fullPath: '/extra-incomes'
      preLoaderRoute: typeof ExtraIncomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts': {
      id: '/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashbacks': {
      id: '/cashbacks'
      path: '/cashbacks'
      fullPath: '/cashbacks'
      preLoaderRoute: typeof CashbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks': {
      id: '/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof BanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared_/$id': {
      id: '/shared_/$id'
      path: '/shared/$id'
      fullPath: '/shared/$id'
      preLoaderRoute: typeof SharedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/payment-checks': {
      id: '/api/public/hooks/payment-checks'
      path: '/api/public/hooks/payment-checks'
      fullPath: '/api/public/hooks/payment-checks'
      preLoaderRoute: typeof ApiPublicHooksPaymentChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-reminders': {
      id: '/api/public/hooks/daily-reminders'
      path: '/api/public/hooks/daily-reminders'
      fullPath: '/api/public/hooks/daily-reminders'
      preLoaderRoute: typeof ApiPublicHooksDailyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cashback-reminders': {
      id: '/api/public/hooks/cashback-reminders'
      path: '/api/public/hooks/cashback-reminders'
      fullPath: '/api/public/hooks/cashback-reminders'
      preLoaderRoute: typeof ApiPublicHooksCashbackRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AiInsightsRoute: AiInsightsRoute,
  AuthRoute: AuthRoute,
  BanksRoute: BanksRoute,
  CalendarRoute: CalendarRoute,
  CashbacksRoute: CashbacksRoute,
  CreditsRoute: CreditsRoute,
  DebtsRoute: DebtsRoute,
  ExtraIncomesRoute: ExtraIncomesRoute,
  GoalsRoute: GoalsRoute,
  ProfileRoute: ProfileRoute,
  RemindersRoute: RemindersRoute,
  SalariesRoute: SalariesRoute,
  SharedRoute: SharedRoute,
  ShiftsRoute: ShiftsRoute,
  StatsRoute: StatsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TransactionsRoute: TransactionsRoute,
  SharedIdRoute: SharedIdRoute,
  ApiPublicHooksCashbackRemindersRoute: ApiPublicHooksCashbackRemindersRoute,
  ApiPublicHooksDailyRemindersRoute: ApiPublicHooksDailyRemindersRoute,
  ApiPublicHooksPaymentChecksRoute: ApiPublicHooksPaymentChecksRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
